type: ancilla #input, gates, ancilla, cc, ca, ac, aa

num_i: 12
num_g: 50

num_a_min: 5
num_a_max: 15
num_a_step: 1

percent_cc: 0.8
percent_ca: 0.05
percent_ac: 0.05
percent_aa: 0.1

fig_path: "no_git"


